GCC = gcc -Wall -g -o

all : 
	$(GCC) Pointers_0 Pointers_0.c
	$(GCC) Pointers_1 Pointers_1.c
	$(GCC) Pointers_2 Pointers_2.c
	$(GCC) Pointers_3 Pointers_3.c
clean :
	rm -rf Pointers_0 Pointers_1 Pointers_2 Pointers_3
