GCC=gcc -g -Wall

all :
	gcc -g -Wall factorial.c -o factorial.exe
	gcc -g -Wall fibonnaci_series.c -o fibonnaci_series.exe
	gcc -g -Wall binary_search.c -o binary_search.exe
	gcc -g -Wall tower_of_hanoi.c -o tower_of_hanoi.exe
#	gcc -g -Wall 

clean :
	rm -rf *.exe
