GCC=gcc -g -Wall

all:
	${GCC} bitwise_01.c -o bitwise_01.exe
	${GCC} alternatePattern.c -o alternatePattern.exe
	${GCC} min_max.c -o min_max.exe
	${GCC} pow_2.c -o pow_2.exe
	${GCC} conditionallySetClearBitsWithoutBranching.c -o conditionallySetClearBitsWithoutBranching.exe
clean :
	rm -rf *.exe
