GCC = gcc -g -Wall

all :
	${GCC} binary_search.c -o binary_search.exe
	${GCC} bubble_sort.c -o bubble_sort.exe
	${GCC} insertion_sort.c -o insertion_sort.exe
	${GCC} linear_search.c -o linear_search.exe
	${GCC} mergesort_linkedlist.c -o mergesort_linkedlist.exe
	${GCC} sample_sort.c -o sample_sort.exe
	${GCC} selection_sort.c -o selection_sort.exe

clean :
	rm -rf *.exe
